// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS6DJQwgwTbS5AkvHUbfpgez-KKQ-yslc',
    appId: '1:929329806341:web:7ea653f01712df0968b06c',
    messagingSenderId: '929329806341',
    projectId: 'chatapp-chatbox',
    authDomain: 'chatapp-chatbox.firebaseapp.com',
    storageBucket: 'chatapp-chatbox.firebasestorage.app',
    measurementId: 'G-3ZQBED8QYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVQq1WakiZd_xcjVN_eQoQbToQvShWegY',
    appId: '1:929329806341:android:89f2bc2e8edf2b6368b06c',
    messagingSenderId: '929329806341',
    projectId: 'chatapp-chatbox',
    storageBucket: 'chatapp-chatbox.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF9VhyI_c99BJSFGC8MO0FsJRuIP0THqI',
    appId: '1:929329806341:ios:9738f02f67946dd368b06c',
    messagingSenderId: '929329806341',
    projectId: 'chatapp-chatbox',
    storageBucket: 'chatapp-chatbox.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF9VhyI_c99BJSFGC8MO0FsJRuIP0THqI',
    appId: '1:929329806341:ios:9738f02f67946dd368b06c',
    messagingSenderId: '929329806341',
    projectId: 'chatapp-chatbox',
    storageBucket: 'chatapp-chatbox.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS6DJQwgwTbS5AkvHUbfpgez-KKQ-yslc',
    appId: '1:929329806341:web:b8c88b045f2ce5ef68b06c',
    messagingSenderId: '929329806341',
    projectId: 'chatapp-chatbox',
    authDomain: 'chatapp-chatbox.firebaseapp.com',
    storageBucket: 'chatapp-chatbox.firebasestorage.app',
    measurementId: 'G-ZS5Y3X4001',
  );
}
